name: My-CI/CD
env:
  WPF_Project_EXE: MyProject.exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  clone:
    runs-on: windows-latest
    
    steps:
      - name: Git_Clone
      - uses: actions/checkout@v3
      - run: start ./Space-Invaders/MyProject/MyProject/bin/Debug/MyProject.exe
